[mypy]
python_version = 3.12
strict = True
exclude = (?x)(^build/|^dist/|^data/)

[mypy-tests.*]
disallow_untyped_defs = False
disallow_untyped_calls = False
ignore_missing_imports = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-jsonschema]
ignore_missing_imports = True

[mypy-streamlit]
ignore_missing_imports = True

[mypy-streamlit_shortcuts]
ignore_missing_imports = True

[mypy-pypinyin]
ignore_missing_imports = True
